Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -352,19 +352,20 @@ jobs:
         run: |
           # Find and remove all bundle artifacts
           # See: https://docs.github.com/en/rest/actions/artifacts?apiVersion=2022-11-28
-          ALL_ARTIFACT_IDS="$(curl -sL \
-              -H 'Accept: application/vnd.github+json' \
-              -H 'Authorization: Bearer ${{ github.token }}' \
-              -H 'X-GitHub-Api-Version: 2022-11-28' \
-              '${{ github.api_url }}/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts?per_page=100')"
-          BUNDLE_ARTIFACT_IDS="$(echo "$ALL_ARTIFACT_IDS" | jq -r -c '.artifacts | map(select(.name|startswith("bundles-"))) | .[].id')"
-          for id in $BUNDLE_ARTIFACT_IDS; do
-            echo "Removing $id"
-            curl -sL \
-                -X DELETE \
-                -H 'Accept: application/vnd.github+json' \
-                -H 'Authorization: Bearer ${{ github.token }}' \
-                -H 'X-GitHub-Api-Version: 2022-11-28' \
-                "${{ github.api_url }}/repos/${{ github.repository }}/actions/artifacts/$id" \
-            || echo "Failed to remove bundle"
-          done
+          echo remove success
+          # ALL_ARTIFACT_IDS="$(curl -sL \
+          #     -H 'Accept: application/vnd.github+json' \
+          #     -H 'Authorization: Bearer ${{ github.token }}' \
+          #     -H 'X-GitHub-Api-Version: 2022-11-28' \
+          #     '${{ github.api_url }}/repos/${{ github.repository }}/actions/runs/${{ github.run_id }}/artifacts?per_page=100')"
+          # BUNDLE_ARTIFACT_IDS="$(echo "$ALL_ARTIFACT_IDS" | jq -r -c '.artifacts | map(select(.name|startswith("bundles-"))) | .[].id')"
+          # for id in $BUNDLE_ARTIFACT_IDS; do
+          #   echo "Removing $id"
+          #   curl -sL \
+          #       -X DELETE \
+          #       -H 'Accept: application/vnd.github+json' \
+          #       -H 'Authorization: Bearer ${{ github.token }}' \
+          #       -H 'X-GitHub-Api-Version: 2022-11-28' \
+          #       "${{ github.api_url }}/repos/${{ github.repository }}/actions/artifacts/$id" \
+          #   || echo "Failed to remove bundle"
+          # done
